// Code generated by generate_api_gateway_routes.py.
// Generated at: 2026-01-01 09:43:49
// Source: services.json
//
// getGeneratedServiceURL switch cases for all services
//
// To regenerate, run:
//   python3 agent/src/fuel2/utils/generate_api_gateway_routes.py


package handlers

import "github.com/ugjb/api-gateway/config"

// getGeneratedServiceURL returns the URL for a given service name
// This function is auto-generated from services.json
// Use config.Service* constants for type-safe service lookups
func (p *ProxyHandler) getGeneratedServiceURL(serviceName string) string {
	switch serviceName {
	// Engineering-Analytics Bounded Context
	case config.ServiceEngineeringAnalytics:
		return p.config.GeneratedServiceURLs.EngineeringAnalytics
	case config.ServiceMetricsCollector:
		return p.config.GeneratedServiceURLs.MetricsCollector
	case config.ServiceKPIEngine:
		return p.config.GeneratedServiceURLs.KPIEngine
	case config.ServiceInsightsDashboard:
		return p.config.GeneratedServiceURLs.InsightsDashboard

	// Goal-Management Bounded Context
	case config.ServiceGoalManagement:
		return p.config.GeneratedServiceURLs.GoalManagement
	case config.ServiceObjectiveService:
		return p.config.GeneratedServiceURLs.ObjectiveService
	case config.ServiceKeyResultTracker:
		return p.config.GeneratedServiceURLs.KeyResultTracker

	// HR-Management Bounded Context
	case config.ServiceHRManagement:
		return p.config.GeneratedServiceURLs.HRManagement
	case config.ServiceEmployeeRegistry:
		return p.config.GeneratedServiceURLs.EmployeeRegistry
	case config.ServiceAllocationEngine:
		return p.config.GeneratedServiceURLs.AllocationEngine

	// Project-Management Bounded Context
	case config.ServiceProjectManagement:
		return p.config.GeneratedServiceURLs.ProjectManagement
	case config.ServiceSprintCoordinator:
		return p.config.GeneratedServiceURLs.SprintCoordinator
	case config.ServiceTaskDispatcher:
		return p.config.GeneratedServiceURLs.TaskDispatcher

	// System-Integration Bounded Context
	case config.ServiceSystemIntegration:
		return p.config.GeneratedServiceURLs.SystemIntegration
	case config.ServiceDataPipeline:
		return p.config.GeneratedServiceURLs.DataPipeline
	case config.ServiceApiGateway:
		return p.config.GeneratedServiceURLs.ApiGateway

	// Workforce-Wellbeing Bounded Context
	case config.ServiceWorkforceWellbeing:
		return p.config.GeneratedServiceURLs.WorkforceWellbeing
	case config.ServiceWellbeingMonitor:
		return p.config.GeneratedServiceURLs.WellbeingMonitor
	case config.ServiceBurnoutPredictor:
		return p.config.GeneratedServiceURLs.BurnoutPredictor

	default:
		return ""
	}
}
