// Code generated by generate_api_gateway_routes.py.
// Generated at: 2026-01-02 14:53:26
// Source: services.json
//
// getGeneratedServiceURL switch cases for all services
//
// To regenerate, run:
//   python3 agent/src/fuel2/utils/generate_api_gateway_routes.py

package handlers

import "github.com/ugjb/api-gateway/config"

// getGeneratedServiceURL returns the URL for a given microservice name
// This function is auto-generated from services.json
// Use config.Service* constants for type-safe service lookups
// Note: Only microservices have URLs - bounded contexts are logical groupings, not deployable services
func (p *ProxyHandler) getGeneratedServiceURL(serviceName string) string {
	switch serviceName {

	// Engineering-Analytics Bounded Context

	case config.ServiceMetricsCollector:
		return p.config.ServiceURLs.MetricsCollector

	case config.ServiceKPIEngine:
		return p.config.ServiceURLs.KPIEngine

	case config.ServiceInsightsDashboard:
		return p.config.ServiceURLs.InsightsDashboard



	// Goal-Management Bounded Context

	case config.ServiceObjectiveService:
		return p.config.ServiceURLs.ObjectiveService

	case config.ServiceKeyResultTracker:
		return p.config.ServiceURLs.KeyResultTracker



	// HR-Management Bounded Context

	case config.ServiceEmployeeRegistry:
		return p.config.ServiceURLs.EmployeeRegistry

	case config.ServiceAllocationEngine:
		return p.config.ServiceURLs.AllocationEngine



	// Project-Management Bounded Context

	case config.ServiceSprintCoordinator:
		return p.config.ServiceURLs.SprintCoordinator

	case config.ServiceTaskDispatcher:
		return p.config.ServiceURLs.TaskDispatcher



	// System-Integration Bounded Context

	case config.ServiceDataPipeline:
		return p.config.ServiceURLs.DataPipeline

	case config.ServiceApiGateway:
		return p.config.ServiceURLs.ApiGateway



	// User-Preferences Bounded Context

	case config.ServicePreferencesService:
		return p.config.ServiceURLs.PreferencesService



	// Workforce-Wellbeing Bounded Context

	case config.ServiceWellbeingMonitor:
		return p.config.ServiceURLs.WellbeingMonitor

	case config.ServiceBurnoutPredictor:
		return p.config.ServiceURLs.BurnoutPredictor



	default:
		return ""
	}
}