// Code generated by generate_api_gateway_routes.py.
// Generated at: 2026-01-02 15:15:01
// Source: services.json
//
// getServiceURL switch cases for all services
//
// To regenerate, run:
//   python3 agent/src/fuel2/utils/generate_api_gateway_routes.py

package handlers

// getServiceURL returns the URL for a given microservice name
// This function is auto-generated from services.json
// Note: Only microservices have URLs - bounded contexts are logical groupings, not deployable services
func (p *ProxyHandler) getServiceURL(serviceName string) string {
	switch serviceName {
	// Infrastructure Services
	case "frontend":
		return p.config.ServiceURLs.Frontend
	case "ollama":
		return p.config.ServiceURLs.Ollama
	case "docker_registry":
		return p.config.ServiceURLs.DockerRegistry
	case "bugsink":
		return p.config.ServiceURLs.Bugsink


	// Engineering-Analytics Bounded Context

	case "metrics_collector":
		return p.config.ServiceURLs.MetricsCollector

	case "k_p_i_engine":
		return p.config.ServiceURLs.KPIEngine

	case "insights_dashboard":
		return p.config.ServiceURLs.InsightsDashboard



	// Goal-Management Bounded Context

	case "objective_service":
		return p.config.ServiceURLs.ObjectiveService

	case "key_result_tracker":
		return p.config.ServiceURLs.KeyResultTracker



	// HR-Management Bounded Context

	case "employee_registry":
		return p.config.ServiceURLs.EmployeeRegistry

	case "allocation_engine":
		return p.config.ServiceURLs.AllocationEngine



	// Project-Management Bounded Context

	case "sprint_coordinator":
		return p.config.ServiceURLs.SprintCoordinator

	case "task_dispatcher":
		return p.config.ServiceURLs.TaskDispatcher



	// System-Integration Bounded Context

	case "data_pipeline":
		return p.config.ServiceURLs.DataPipeline

	case "api_gateway":
		return p.config.ServiceURLs.ApiGateway



	// User-Preferences Bounded Context

	case "preferences_service":
		return p.config.ServiceURLs.PreferencesService



	// Workforce-Wellbeing Bounded Context

	case "wellbeing_monitor":
		return p.config.ServiceURLs.WellbeingMonitor

	case "burnout_predictor":
		return p.config.ServiceURLs.BurnoutPredictor



	default:
		return ""
	}
}